### ISSUE TITLE
Problem solving for "ld: library not found for -llibopenblas"

### ISSUE THREAD

**Issue by hustlingFive** [jpferrierjr/Apple-Silicon-GPAW-setup#1]
When I using this script, there will show this error during `pip install gpaw`.
```
ld: library not found for -llibopenblas
```

And I have solved this problem by replacing
```
libraries += ['libopenblas']
libraries += ['libxc']
libraries += ['libmpi']
libraries += ['libscalapack']
```
with
```
libraries += ['openblas']
libraries += ['xc']
libraries += ['mpi']
libraries += ['scalapack']
```

I got this idea on [GPAW Homebrew installation](https://wiki.fysik.dtu.dk/gpaw/platforms/MacOSX/homebrew.html).

**Comment by jpferrierjr** [comment]
Thanks! The new homebrew update changed it all. :/ I was getting the same error too. I'll make the switch.

On Dec 7, 2022, at 8:49 PM, hustlingFive ***@***.***> wrote:



When I using this script, there will show this error during pip install gpaw.

ld: library not found for -llibopenblas


And I have solved this problem by replacing

libraries += ['libopenblas']
libraries += ['libxc']
libraries += ['libmpi']
libraries += ['libscalapack']


with

libraries += ['openblas']
libraries += ['xc']
libraries += ['mpi']
libraries += ['scalapack']


I got this idea on GPAW Homebrew installation<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.fysik.dtu.dk%2Fgpaw%2Fplatforms%2FMacOSX%2Fhomebrew.html&data=05%7C01%7C%7Ce63adcf5a04a400e78fa08dad8be732e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638060609742503317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7jAu3uBg8jwVAVl7SUAHIDiO9F9i%2FilQuq3ca%2FkrvvQ%3D&reserved=0>.
