### ISSUE TITLE
Error when installing m1max

### ISSUE THREAD

**Issue by JYG0620** [jpferrierjr/Apple-Silicon-GPAW-setup#3]
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED test_imports.py::test_imports - pytest.PytestRemovedIn8Warning: Passing None has been deprecated.
FAILED test_units.py::test_units[2002] - assert None is not None
FAILED test_units.py::test_units[2006] - assert None is not None
FAILED test_units.py::test_units[2010] - assert None is not None
FAILED test_units.py::test_units[2014] - assert None is not None
FAILED calculator/castep/test_castep_interface.py::test_fundamental_params - pytest.PytestRemovedIn8Warning: Passing None has been deprecated.
FAILED cli/test_bandstructure.py::test_ase_bandstructure - assert (1 != 0) == False
FAILED db/test_db_web.py::test_favicon - AssertionError: assert 204 == 308
FAILED fio/test_animate.py::test_animate - UserWarning: You passed in an explicit save_count=100 which is being ignore...
FAILED optimize/test_optimizers.py::test_optimize[MDMin] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[FIRE] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[LBFGS] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[LBFGSLineSearch] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[BFGSLineSearch] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[BFGS] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[GoodOldQuasiNewton] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[GPMin] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[SciPyFminCG] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[SciPyFminBFGS] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[PreconLBFGS] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[PreconFIRE] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[ODE12r] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
FAILED optimize/test_optimizers.py::test_optimize[PreconODE12r] - pytest.PytestReturnNotNoneWarning: Expected None, but optimize/test_optimiz...
ERROR calculator/vasp/test_vasp_calculator.py::test_verify_no_run
ERROR calculator/vasp/test_vasp_calculator.py::test_check_atoms
ERROR calculator/vasp/test_vasp_calculator.py::test_not_atoms[None]
ERROR calculator/vasp/test_vasp_calculator.py::test_not_atoms[a_string]
ERROR calculator/vasp/test_vasp_calculator.py::test_not_atoms[bad_atoms2]
ERROR calculator/vasp/test_vasp_calculator.py::test_bad_pbc[pbc0]
ERROR calculator/vasp/test_vasp_calculator.py::test_bad_pbc[pbc1]
ERROR calculator/vasp/test_vasp_calculator.py::test_bad_pbc[pbc2]
ERROR calculator/vasp/test_vasp_calculator.py::test_vasp_no_cell
ERROR calculator/vasp/test_vasp_calculator.py::test_vasp_name
ERROR calculator/vasp/test_vasp_calculator.py::test_vasp_get_calculator
ERROR calculator/vasp/test_vasp_calculator.py::test_make_command_envvar[ASE_VASP_COMMAND]
ERROR calculator/vasp/test_vasp_calculator.py::test_make_command_envvar[VASP_COMMAND]
ERROR calculator/vasp/test_vasp_calculator.py::test_make_command_envvar[VASP_SCRIPT]
ERROR calculator/vasp/test_vasp_calculator.py::test_make_command_no_envvar
ERROR calculator/vasp/test_vasp_calculator.py::test_make_command_explicit
ERROR vibrations/test_vib.py::TestHarmonicVibrations::test_harmonic_vibrations - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestHarmonicVibrations::test_consistency_with_vibrationsdata - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestHarmonicVibrations::test_json_manipulation - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestHarmonicVibrations::test_vibrations_methods - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestHarmonicVibrations::test_vibrations_restart_dir - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_init - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_energies_and_modes - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_imaginary_energies - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_zero_mass - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_new_mass - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_fixed_atoms - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_dos - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_pdos - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_todict - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_dict_roundtrip - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_dict_indices[indices0-expected_mask0] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_dict_indices[None-expected_mask1] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_jmol_roundtrip - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_bad_hessian - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
ERROR vibrations/test_vib.py::TestVibrationsData::test_bad_hessian2d - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and wi...
= 23 failed, 1594 passed, 302 skipped, 2 xfailed, 2 xpassed, 3 warnings, 36 errors in 102.22s (0:01:42) =
Cloning into 'gpaw'...

Thanks for making a nice script, but I'm having problems with ase

**Comment by jpferrierjr** [comment]
Unfortunately, these are issues with ASE that I can't resolve, as my code just installs the current version of ASE. There are also issues in the test in ASE with pytest itself. But, this doesn't really mean too much for you. It should still work fine.

A good way to test is to open up your terminal and type:
```
conda activate [the_env_you_created]
ase -h
```

If it responds with a list of commands, then ASE is installed correctly.

**Comment by JYG0620** [comment]
I did what you said and it worked fine, the calculation seems to be working
too thank you

2023년 3월 22일 (수) 오전 8:11, John Ferrier ***@***.***>님이 작성:
